### PR TITLE
Fix divide by zero for empty files

### PR DESCRIPTION
**Pull request by rlmv**
# Description

Fix a divide-by-zero error when computing progress for file uploads.

## Github Issue

[ISSUE-NUMBER](issue-url)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added unit tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by rlmv** [comment]
Good question. Empty files are sometimes semantically useful, eg Python __init__.py files. We're not Github though, so maybe that doesn't matter.

**Comment by rlmv** [comment]
@merky addressed. I added a `SKIPPED` status to the progress bar for empty files so people have some noticed of what is going on.

**Comment by merky** [comment]
@rlmv Excellent! Looks great

**Comment by rlmv** [comment]
@merky I realized that I wasn't actually skipping the upload here - just happily *saying* that I was. Trying to both show the file as skipped in the progress bar, and also avoid hitting the `upload_complete` endpoint for empty files becomes a bit of a mess - it needs a little more refactoring than I have time for right now. I think best course of action is to fix the divide-by-zero error for now, and add a ticket for sorting out empty file logic later. I'm also not totally convinced we need to skip empty files.

What do you think about that?

**Comment by merky** [comment]
@rlmv Ah, I didn't catch that either! :) Agreed, on all fronts.

**Pull request merged**
