### PR TITLE
ignoring windows prefix

### PR DESCRIPTION
**Pull request by JeremyLecoeur**
# Description

Windows sometimes return the file path with "\\?\" in front, which confuses the upload manager and cause the upload to never "finish" since we never update the status of the file

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

By uploading directories from both windows and mac machines

### CODE REVIEW

**Comment by JeremyLecoeur** [comment]
the \\? is a prefix for filepaths that are long (not sure how it works though)

**Comment by rlmv** [comment]
Right, but where is that value being introduced? Is it being returned to the Python client from the Agent, or is the Python client getting it when it makes sys calls to build the initial list of target files? Just curious because it might change the best place to put this conversion.

**Comment by JeremyLecoeur** [comment]
It comes from the response of the agent

**Comment by rlmv** [comment]
Ok 👍

**Pull request merged**
