### PR TITLE
APP-1041: Fix Annotation Layer Deletion

### PR DESCRIPTION
**Pull request by mattusifer**

### CODE REVIEW

**Comment by mistyahmed** [comment]
Just to confirm, will the issue with deletion of annotations be addressed in a separate PR?

**Comment by mistyahmed** [comment]
@mattusifer Thanks for the explanation!  I think you can make a similar change here: https://github.com/Blackfynn/blackfynn-python/blob/534b4f10270ba2f87288bbb34f7767c3f56e30cd/blackfynn/api/timeseries.py#L569

**Comment by mattusifer** [comment]
Good catch! I'll make that change as part of this PR :+1:

**Comment by mattusifer** [comment]
I noticed there were a number of commented-out tests that were supposed to be testing deletion functionality, so I simply uncommented those instead of writing new tests.

**Pull request merged**
